// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3y--R95kofsHbLpwzv2Ei1sdJm-8r7Nc',
    appId: '1:836739878149:web:dc42d4980df2f3e4ecbb6c',
    messagingSenderId: '836739878149',
    projectId: 'bike-rental-3747d',
    authDomain: 'bike-rental-3747d.firebaseapp.com',
    databaseURL: 'https://bike-rental-3747d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bike-rental-3747d.firebasestorage.app',
    measurementId: 'G-F3YFWLFB9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnhVULHKqFfJ2JmIn3xb0C8nntLjCWtM',
    appId: '1:836739878149:android:b59eec4b22b5b57fecbb6c',
    messagingSenderId: '836739878149',
    projectId: 'bike-rental-3747d',
    databaseURL: 'https://bike-rental-3747d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bike-rental-3747d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbL14Xikf4wpCtG6QmoGoMETLoW2yMwSI',
    appId: '1:836739878149:ios:d9ffa61a49de5792ecbb6c',
    messagingSenderId: '836739878149',
    projectId: 'bike-rental-3747d',
    databaseURL: 'https://bike-rental-3747d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bike-rental-3747d.firebasestorage.app',
    iosBundleId: 'com.example.bikeRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbL14Xikf4wpCtG6QmoGoMETLoW2yMwSI',
    appId: '1:836739878149:ios:d9ffa61a49de5792ecbb6c',
    messagingSenderId: '836739878149',
    projectId: 'bike-rental-3747d',
    databaseURL: 'https://bike-rental-3747d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bike-rental-3747d.firebasestorage.app',
    iosBundleId: 'com.example.bikeRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3y--R95kofsHbLpwzv2Ei1sdJm-8r7Nc',
    appId: '1:836739878149:web:b985917411c8929fecbb6c',
    messagingSenderId: '836739878149',
    projectId: 'bike-rental-3747d',
    authDomain: 'bike-rental-3747d.firebaseapp.com',
    databaseURL: 'https://bike-rental-3747d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bike-rental-3747d.firebasestorage.app',
    measurementId: 'G-Y8J5CN9H64',
  );
}
